databases:
  - name: production
    databaseName: recipe_app_production
    user: <%= ENV["RENDER_DATABASE_USERNAME"] %>
    password: <%= ENV["RENDER_DATABASE_PASSWORD"] %>

services:
  - type: web
    name: Recipe-App
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
